# Generated by Django 5.1.7 on 2025-04-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='episodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collaborators/')),
                ('title', models.CharField(max_length=255)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='events.episode')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='events.event'),
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moments/')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='events.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='participants/')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.episode')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='performances/')),
                ('title', models.CharField(max_length=255)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_performances', to='events.episode')),
            ],
        ),
    ]
