# Generated by Django 6.0.3 on 2026-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('felix', 'Felix'), ('luna', 'Luna'), ('max', 'Max'), ('zoe', 'Zoe'), ('alex', 'Alex'), ('taylor', 'Taylor'), ('jordan', 'Jordan'), ('casey', 'Casey'), ('river', 'River'), ('sage', 'Sage')], max_length=50),
        ),
    ]
