# Generated by Django 6.0.3 on 2026-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
